/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.telnyx.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * ConferenceUnholdRequest
 */
@JsonPropertyOrder({
  ConferenceUnholdRequest.JSON_PROPERTY_CALL_CONTROL_IDS
})
@JsonTypeName("ConferenceUnholdRequest")
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ConferenceUnholdRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_CALL_CONTROL_IDS = "call_control_ids";
  private List<String> callControlIds = new ArrayList<>();


  public ConferenceUnholdRequest callControlIds(List<String> callControlIds) {
    
    this.callControlIds = callControlIds;
    return this;
  }

  public ConferenceUnholdRequest addCallControlIdsItem(String callControlIdsItem) {
    this.callControlIds.add(callControlIdsItem);
    return this;
  }

   /**
   * List of unique identifiers and tokens for controlling the call. Enter each call control ID to be unheld.
   * @return callControlIds
  **/
  @ApiModelProperty(required = true, value = "List of unique identifiers and tokens for controlling the call. Enter each call control ID to be unheld.")
  @JsonProperty(JSON_PROPERTY_CALL_CONTROL_IDS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getCallControlIds() {
    return callControlIds;
  }


  public void setCallControlIds(List<String> callControlIds) {
    this.callControlIds = callControlIds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConferenceUnholdRequest conferenceUnholdRequest = (ConferenceUnholdRequest) o;
    return Objects.equals(this.callControlIds, conferenceUnholdRequest.callControlIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callControlIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConferenceUnholdRequest {\n");
    sb.append("    callControlIds: ").append(toIndentedString(callControlIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

