/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Sets the type of DTMF digits sent from Telnyx to this Connection. Note that DTMF digits sent to Telnyx will be accepted in all formats.
 */
@JsonAdapter(DtmfType.Adapter.class)
public enum DtmfType {
  RFC_2833("RFC 2833"),
  INBAND("Inband"),
  SIP_INFO("SIP INFO");

  private String value;

  DtmfType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DtmfType fromValue(String text) {
    for (DtmfType b : DtmfType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DtmfType> {
    @Override
    public void write(final JsonWriter jsonWriter, final DtmfType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DtmfType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DtmfType.fromValue(String.valueOf(value));
    }
  }
}
