/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * FaxApplicationOutbound
 */


public class FaxApplicationOutbound {
  @SerializedName("channel_limit")
  private Integer channelLimit = null;

  @SerializedName("outbound_voice_profile_id")
  private String outboundVoiceProfileId = null;

  public FaxApplicationOutbound channelLimit(Integer channelLimit) {
    this.channelLimit = channelLimit;
    return this;
  }

   /**
   * When set, this will limit the number of concurrent outbound calls to phone numbers associated with this connection.
   * @return channelLimit
  **/
  @Schema(example = "10", description = "When set, this will limit the number of concurrent outbound calls to phone numbers associated with this connection.")
  public Integer getChannelLimit() {
    return channelLimit;
  }

  public void setChannelLimit(Integer channelLimit) {
    this.channelLimit = channelLimit;
  }

  public FaxApplicationOutbound outboundVoiceProfileId(String outboundVoiceProfileId) {
    this.outboundVoiceProfileId = outboundVoiceProfileId;
    return this;
  }

   /**
   * Get outboundVoiceProfileId
   * @return outboundVoiceProfileId
  **/
  @Schema(description = "")
  public String getOutboundVoiceProfileId() {
    return outboundVoiceProfileId;
  }

  public void setOutboundVoiceProfileId(String outboundVoiceProfileId) {
    this.outboundVoiceProfileId = outboundVoiceProfileId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaxApplicationOutbound faxApplicationOutbound = (FaxApplicationOutbound) o;
    return Objects.equals(this.channelLimit, faxApplicationOutbound.channelLimit) &&
        Objects.equals(this.outboundVoiceProfileId, faxApplicationOutbound.outboundVoiceProfileId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channelLimit, outboundVoiceProfileId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaxApplicationOutbound {\n");
    
    sb.append("    channelLimit: ").append(toIndentedString(channelLimit)).append("\n");
    sb.append("    outboundVoiceProfileId: ").append(toIndentedString(outboundVoiceProfileId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
