/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.models;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.v3.oas.annotations.media.Schema;
import com.google.gson.annotations.SerializedName;
import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Determines which webhook format will be used, Telnyx API v1 or v2.
 */
@JsonAdapter(WebhookApiVersion.Adapter.class)
public enum WebhookApiVersion {
  _1("1"),
  _2("2");

  private String value;

  WebhookApiVersion(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WebhookApiVersion fromValue(String text) {
    for (WebhookApiVersion b : WebhookApiVersion.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WebhookApiVersion> {
    @Override
    public void write(final JsonWriter jsonWriter, final WebhookApiVersion enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WebhookApiVersion read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WebhookApiVersion.fromValue(String.valueOf(value));
    }
  }
}
