/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.apis;

import com.telnyx.sdk.ApiException;
import com.telnyx.sdk.models.ConnectionResponse;
import com.telnyx.sdk.models.ListConnectionsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConnectionsApi
 */
@Ignore
public class ConnectionsApiTest {

    private final ConnectionsApi api = new ConnectionsApi();

    /**
     * List connections
     *
     * Returns a list of your connections irrespective of type.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listConnectionsTest() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        String filterConnectionNameContains = null;
        String filterOutboundVoiceProfileId = null;
        String sort = null;
        ListConnectionsResponse response = api.listConnections(pageNumber, pageSize, filterConnectionNameContains, filterOutboundVoiceProfileId, sort);

        // TODO: test validations
    }
    /**
     * Retrieve a connection
     *
     * Retrieves the high-level details of an existing connection. To retrieve specific authentication information, use the endpoint for the specific connection type.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveConnectionTest() throws ApiException {
        String id = null;
        ConnectionResponse response = api.retrieveConnection(id);

        // TODO: test validations
    }
}
