/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.apis;

import com.telnyx.sdk.ApiException;
import com.telnyx.sdk.models.CreateCredentialConnectionRequest;
import com.telnyx.sdk.models.CredentialConnectionResponse;
import com.telnyx.sdk.models.ListCredentialConnectionsResponse;
import com.telnyx.sdk.models.UpdateCredentialConnectionRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CredentialConnectionsApi
 */
@Ignore
public class CredentialConnectionsApiTest {

    private final CredentialConnectionsApi api = new CredentialConnectionsApi();

    /**
     * Create a credential connection
     *
     * Creates a credential connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCredentialConnectionTest() throws ApiException {
        CreateCredentialConnectionRequest body = null;
        CredentialConnectionResponse response = api.createCredentialConnection(body);

        // TODO: test validations
    }
    /**
     * Delete a credential connection
     *
     * Deletes an existing credential connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCredentialConnectionTest() throws ApiException {
        String id = null;
        CredentialConnectionResponse response = api.deleteCredentialConnection(id);

        // TODO: test validations
    }
    /**
     * List credential connections
     *
     * Returns a list of your credential connections.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCredentialConnectionsTest() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        String filterConnectionNameContains = null;
        String filterOutboundOutboundVoiceProfileId = null;
        String sort = null;
        ListCredentialConnectionsResponse response = api.listCredentialConnections(pageNumber, pageSize, filterConnectionNameContains, filterOutboundOutboundVoiceProfileId, sort);

        // TODO: test validations
    }
    /**
     * Retrieve a connection
     *
     * Retrieves the details of an existing credential connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveCredentialConnectionTest() throws ApiException {
        String id = null;
        CredentialConnectionResponse response = api.retrieveCredentialConnection(id);

        // TODO: test validations
    }
    /**
     * Update a credential connection
     *
     * Updates settings of an existing credential connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCredentialConnectionTest() throws ApiException {
        UpdateCredentialConnectionRequest body = null;
        String id = null;
        CredentialConnectionResponse response = api.updateCredentialConnection(body, id);

        // TODO: test validations
    }
}
