/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.apis;

import com.telnyx.sdk.ApiException;
import com.telnyx.sdk.models.CreateFqdnConnectionRequest;
import com.telnyx.sdk.models.FqdnConnectionResponse;
import com.telnyx.sdk.models.ListFqdnConnectionsResponse;
import com.telnyx.sdk.models.UpdateFqdnConnectionRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FqdnConnectionsApi
 */
@Ignore
public class FqdnConnectionsApiTest {

    private final FqdnConnectionsApi api = new FqdnConnectionsApi();

    /**
     * Create an Fqdn connection
     *
     * Creates a FQDN connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFqdnConnectionTest() throws ApiException {
        CreateFqdnConnectionRequest body = null;
        FqdnConnectionResponse response = api.createFqdnConnection(body);

        // TODO: test validations
    }
    /**
     * Delete an Fqdn connection
     *
     * Deletes an FQDN connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFqdnConnectionTest() throws ApiException {
        String id = null;
        FqdnConnectionResponse response = api.deleteFqdnConnection(id);

        // TODO: test validations
    }
    /**
     * List Fqdn connections
     *
     * Returns a list of your FQDN connections.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFqdnConnectionsTest() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        String filterConnectionNameContains = null;
        String sort = null;
        ListFqdnConnectionsResponse response = api.listFqdnConnections(pageNumber, pageSize, filterConnectionNameContains, sort);

        // TODO: test validations
    }
    /**
     * Retrieve an Fqdn connection
     *
     * Retrieves the details of an existing FQDN connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveFqdnConnectionTest() throws ApiException {
        String id = null;
        FqdnConnectionResponse response = api.retrieveFqdnConnection(id);

        // TODO: test validations
    }
    /**
     * Update an Fqdn connection
     *
     * Updates settings of an existing FQDN connection.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFqdnConnectionTest() throws ApiException {
        UpdateFqdnConnectionRequest body = null;
        String id = null;
        FqdnConnectionResponse response = api.updateFqdnConnection(body, id);

        // TODO: test validations
    }
}
