/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.apis;

import com.telnyx.sdk.ApiException;
import com.telnyx.sdk.models.CreateFaxApplicationRequest;
import com.telnyx.sdk.models.InlineResponse2001;
import com.telnyx.sdk.models.InlineResponse2011;
import com.telnyx.sdk.models.UpdateFaxApplicationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProgrammableFaxApplicationsApi
 */
@Ignore
public class ProgrammableFaxApplicationsApiTest {

    private final ProgrammableFaxApplicationsApi api = new ProgrammableFaxApplicationsApi();

    /**
     * Creates a Fax Application
     *
     * Creates a new Fax Application based on the parameters sent in the request. The application name and webhook URL are required. Once created, you can assign phone numbers to your application using the &#x60;/phone_numbers&#x60; endpoint.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFaxApplicationTest() throws ApiException {
        CreateFaxApplicationRequest body = null;
        InlineResponse2011 response = api.createFaxApplication(body);

        // TODO: test validations
    }
    /**
     * Deletes a Fax Application
     *
     * Permanently deletes a Fax Application. Deletion may be prevented if the application is in use by phone numbers.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFaxApplicationTest() throws ApiException {
        String id = null;
        InlineResponse2011 response = api.deleteFaxApplication(id);

        // TODO: test validations
    }
    /**
     * Retrieve a Fax Application
     *
     * Return the details of an existing Fax Application inside the &#x27;data&#x27; attribute of the response.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFaxApplicationTest() throws ApiException {
        String id = null;
        InlineResponse2011 response = api.getFaxApplication(id);

        // TODO: test validations
    }
    /**
     * List all Fax Applications
     *
     * This endpoint returns a list of your Fax Applications inside the &#x27;data&#x27; attribute of the response. You can adjust which applications are listed by using filters. Fax Applications are used to configure how you send and receive faxes using the Programmable Fax API with Telnyx.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFaxApplicationsTest() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        String filterApplicationNameContains = null;
        String filterOutboundOutboundVoiceProfileId = null;
        String sort = null;
        InlineResponse2001 response = api.listFaxApplications(pageNumber, pageSize, filterApplicationNameContains, filterOutboundOutboundVoiceProfileId, sort);

        // TODO: test validations
    }
    /**
     * Update a Fax Application
     *
     * Updates settings of an existing Fax Application based on the parameters of the request.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFaxApplicationTest() throws ApiException {
        UpdateFaxApplicationRequest body = null;
        String id = null;
        InlineResponse2011 response = api.updateFaxApplication(body, id);

        // TODO: test validations
    }
}
