/*
 * Telnyx API
 * SIP trunking, SMS, MMS, Call Control and Telephony Data Services.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@telnyx.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.telnyx.sdk.apis;

import com.telnyx.sdk.ApiException;
import com.telnyx.sdk.models.CreateTexmlApplicationRequest;
import com.telnyx.sdk.models.InlineResponse200;
import com.telnyx.sdk.models.InlineResponse201;
import com.telnyx.sdk.models.UpdateTexmlApplicationRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TeXmlApplicationsApi
 */
@Ignore
public class TeXmlApplicationsApiTest {

    private final TeXmlApplicationsApi api = new TeXmlApplicationsApi();

    /**
     * Creates a TeXML Application
     *
     * Creates a TeXML Application.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTexmlApplicationTest() throws ApiException {
        CreateTexmlApplicationRequest body = null;
        InlineResponse201 response = api.createTexmlApplication(body);

        // TODO: test validations
    }
    /**
     * Deletes a TeXML Application
     *
     * Deletes a TeXML Application.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteTexmlApplicationTest() throws ApiException {
        String id = null;
        InlineResponse201 response = api.deleteTexmlApplication(id);

        // TODO: test validations
    }
    /**
     * List all TeXML Applications
     *
     * Returns a list of your TeXML Applications.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findTexmlApplicationsTest() throws ApiException {
        Integer pageNumber = null;
        Integer pageSize = null;
        String filterFriendlyNameContains = null;
        String filterOutboundOutboundVoiceProfileId = null;
        String sort = null;
        InlineResponse200 response = api.findTexmlApplications(pageNumber, pageSize, filterFriendlyNameContains, filterOutboundOutboundVoiceProfileId, sort);

        // TODO: test validations
    }
    /**
     * Retrieve a TeXML Application
     *
     * Retrieves the details of an existing TeXML Application.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTexmlApplicationTest() throws ApiException {
        String id = null;
        InlineResponse201 response = api.getTexmlApplication(id);

        // TODO: test validations
    }
    /**
     * Update a TeXML Application
     *
     * Updates settings of an existing TeXML Application.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTexmlApplicationTest() throws ApiException {
        UpdateTexmlApplicationRequest body = null;
        String id = null;
        InlineResponse201 response = api.updateTexmlApplication(body, id);

        // TODO: test validations
    }
}
